#ifndef PCI_H
#define PCI_H

#include <stdint.h>

#define PCI_CONFIG_ADDRESS 0x0cf8
#define PCI_CONFIG_DATA 0x0cfc

typedef enum : uint8_t
{
	PCI_DEVICE_CLASS_UNCLASSIFIED = 0x0,
	PCI_DEVICE_CLASS_MASS_STORAGE_CONTROLLER = 0x1,
	PCI_DEVICE_CLASS_NETWORK_CONTROLLER = 0x2,
	PCI_DEVICE_CLASS_DISPLAY_CONTROLLER = 0x3,
	PCI_DEVICE_CLASS_MULTIMEDIA_CONTROLLER = 0x4,
	PCI_DEVICE_CLASS_MEMORY_CONTROLLER = 0x5,
	PCI_DEVICE_CLASS_BRIDGE = 0x6,
	PCI_DEVICE_CLASS_SIMPLE_COMMUNICATION_CONTROLLER = 0x7,
	PCI_DEVICE_CLASS_BASE_SYSTEM_PERIPHERAL = 0x8,
	PCI_DEVICE_CLASS_INPUT_DEVICE_CONTROLLER = 0x9,
	PCI_DEVICE_CLASS_DOCKING_STATION = 0xa,
	PCI_DEVICE_CLASS_PROCESSOR = 0xb,
	PCI_DEVICE_CLASS_SERIAL_BUS_CONTROLLER = 0xc,
	PCI_DEVICE_CLASS_WIRELESS_CONTROLLER = 0xd,
	PCI_DEVICE_CLASS_INTELLIGENT_CONTROLLER = 0xe,
	PCI_DEVICE_CLASS_SATELLITE_COMMUNICATION_CONTROLLER = 0xf,
	PCI_DEVICE_CLASS_ENCRYPTION_CONTROLLER = 0x10,
	PCI_DEVICE_CLASS_SIGNAL_PROCESSING_CONTROLLER = 0x11,
	PCI_DEVICE_CLASS_PROCESSING_ACCELERATOR = 0x12,
	PCI_DEVICE_CLASS_NON_ESSENTIAL_INSTRUMENTATION = 0x13,
	PCI_DEVICE_CLASS_CO_PROCESSOR = 0x40,
} DeviceClass;

typedef enum : uint16_t
{
	PCI_DEVICE_SUBCLASS_UNCLASSIFIED_NON_VGA_COMPATIBLE = 0x0000,
	PCI_DEVICE_SUBCLASS_UNCLASSIFIED_VGA_COMPATIBLE = 0x0001,

	PCI_DEVICE_SUBCLASS_MASS_STORAGE_CONTROLLER_SCSI_BUS= 0x0100,
	PCI_DEVICE_SUBCLASS_MASS_STORAGE_CONTROLLER_IDE= 0x0101,
	PCI_DEVICE_SUBCLASS_MASS_STORAGE_CONTROLLER_FLOPPY_DISK= 0x0102,
	PCI_DEVICE_SUBCLASS_MASS_STORAGE_CONTROLLER_IPI_BUS= 0x0103,
	PCI_DEVICE_SUBCLASS_MASS_STORAGE_CONTROLLER_RAID= 0x0104,
	PCI_DEVICE_SUBCLASS_MASS_STORAGE_CONTROLLER_ATA= 0x0105,
	PCI_DEVICE_SUBCLASS_MASS_STORAGE_CONTROLLER_SERIAL_ATA= 0x0106,
	PCI_DEVICE_SUBCLASS_MASS_STORAGE_CONTROLLER_SERIAL_ATTACHED_SCSI= 0x0107,
	PCI_DEVICE_SUBCLASS_MASS_STORAGE_CONTROLLER_NON_VOLATILE_MEMORY= 0x0108,
	PCI_DEVICE_SUBCLASS_MASS_STORAGE_CONTROLLER_OTHER = 0x0180,

	PCI_DEVICE_SUBCLASS_NETWORK_CONTROLLER_ETHERNET= 0x0200,
	PCI_DEVICE_SUBCLASS_NETWORK_CONTROLLER_TOKEN_RING= 0x0201,
	PCI_DEVICE_SUBCLASS_NETWORK_CONTROLLER_FDDI= 0x0202,
	PCI_DEVICE_SUBCLASS_NETWORK_CONTROLLER_ATM= 0x0203,
	PCI_DEVICE_SUBCLASS_NETWORK_CONTROLLER_ISDN= 0x0204,
	PCI_DEVICE_SUBCLASS_NETWORK_CONTROLLER_WORLD_FIP= 0x0205,
	PCI_DEVICE_SUBCLASS_NETWORK_CONTROLLER_PICMG_MULTI_COMPUTING= 0x0206,
	PCI_DEVICE_SUBCLASS_NETWORK_CONTROLLER_INFINIBAND= 0x0207,
	PCI_DEVICE_SUBCLASS_NETWORK_CONTROLLER_FABRIC= 0x0208,
	PCI_DEVICE_SUBCLASS_NETWORK_CONTROLLER_OTHER = 0x0280,

	PCI_DEVICE_SUBCLASS_DISPLAY_CONTROLLER_VGA_COMPATIBLE= 0x0300,
	PCI_DEVICE_SUBCLASS_DISPLAY_CONTROLLER_XGA= 0x0301,
	PCI_DEVICE_SUBCLASS_DISPLAY_CONTROLLER_3D= 0x0302,
	PCI_DEVICE_SUBCLASS_DISPLAY_CONTROLLER_OTHER = 0x0380,

	PCI_DEVICE_SUBCLASS_MULTIMEDIA_CONTROLLER_MULTIMEDIA_VIDEO= 0x0400,
	PCI_DEVICE_SUBCLASS_MULTIMEDIA_CONTROLLER_MULTIMEDIA_AUDIO= 0x0401,
	PCI_DEVICE_SUBCLASS_MULTIMEDIA_CONTROLLER_COMPUTER_TELEPHONY_DEVICE = 0x0402,
	PCI_DEVICE_SUBCLASS_MULTIMEDIA_CONTROLLER_AUDIO_DEVICE = 0x0403,
	PCI_DEVICE_SUBCLASS_MULTIMEDIA_CONTROLLER_OTHER = 0x0480,

	PCI_DEVICE_SUBCLASS_MEMORY_CONTROLLER_RAM = 0x0500,
	PCI_DEVICE_SUBCLASS_MEMORY_CONTROLLER_FLASH = 0x0501,
	PCI_DEVICE_SUBCLASS_MEMORY_CONTROLLER_OTHER = 0x0580,

	PCI_DEVICE_SUBCLASS_BRIDGE_HOST= 0x0600,
	PCI_DEVICE_SUBCLASS_BRIDGE_ISA= 0x0601,
	PCI_DEVICE_SUBCLASS_BRIDGE_EISA= 0x0602,
	PCI_DEVICE_SUBCLASS_BRIDGE_MCA= 0x0603,
	PCI_DEVICE_SUBCLASS_BRIDGE_PCI_TO_PCI1 = 0x0604,
	PCI_DEVICE_SUBCLASS_BRIDGE_PCMCIA= 0x0605,
	PCI_DEVICE_SUBCLASS_BRIDGE_NUBUS= 0x0606,
	PCI_DEVICE_SUBCLASS_BRIDGE_CARDBUS= 0x0607,
	PCI_DEVICE_SUBCLASS_BRIDGE_RAC_EWAY= 0x0608,
	PCI_DEVICE_SUBCLASS_BRIDGE_PCI_TO_PCI2 = 0x0609,
	PCI_DEVICE_SUBCLASS_BRIDGE_INFINIBAND_TO_PCI_HOST= 0x060A,
	PCI_DEVICE_SUBCLASS_BRIDGE_OTHER = 0x0680,

	PCI_DEVICE_SUBCLASS_SIMPLE_COMMUNICATION_CONTROLLER_SERIAL= 0x0700,
	PCI_DEVICE_SUBCLASS_SIMPLE_COMMUNICATION_CONTROLLER_PARALLEL= 0x0701,
	PCI_DEVICE_SUBCLASS_SIMPLE_COMMUNICATION_CONTROLLER_MULTIPORT_SERIAL= 0x0702,
	PCI_DEVICE_SUBCLASS_SIMPLE_COMMUNICATION_CONTROLLER_MODEM = 0x0703,
	PCI_DEVICE_SUBCLASS_SIMPLE_COMMUNICATION_CONTROLLER_GPIB= 0x0704,
	PCI_DEVICE_SUBCLASS_SIMPLE_COMMUNICATION_CONTROLLER_SMART_CARD= 0x0705,
	PCI_DEVICE_SUBCLASS_SIMPLE_COMMUNICATION_CONTROLLER_OTHER = 0x0780,

	PCI_DEVICE_SUBCLASS_BASE_SYSTEM_PERIPHERAL_PIC = 0x0800,
	PCI_DEVICE_SUBCLASS_BASE_SYSTEM_PERIPHERAL_DMA = 0x0801,
	PCI_DEVICE_SUBCLASS_BASE_SYSTEM_PERIPHERAL_TIMER = 0x0802,
	PCI_DEVICE_SUBCLASS_BASE_SYSTEM_PERIPHERAL_RTC = 0x0803,
	PCI_DEVICE_SUBCLASS_BASE_SYSTEM_PERIPHERAL_PCI_HOT_PLUG = 0x0804,
	PCI_DEVICE_SUBCLASS_BASE_SYSTEM_PERIPHERAL_SD_HOST = 0x0805,
	PCI_DEVICE_SUBCLASS_BASE_SYSTEM_PERIPHERAL_IOMMU = 0x0806,
	PCI_DEVICE_SUBCLASS_BASE_SYSTEM_PERIPHERAL_OTHER = 0x0880,

	PCI_DEVICE_SUBCLASS_INPUT_DEVICE_CONTROLLER_KEYBOARD = 0x0900,
	PCI_DEVICE_SUBCLASS_INPUT_DEVICE_CONTROLLER_DIGITIZER_PEN = 0x0901,
	PCI_DEVICE_SUBCLASS_INPUT_DEVICE_CONTROLLER_MOUSE = 0x0902,
	PCI_DEVICE_SUBCLASS_INPUT_DEVICE_CONTROLLER_SCANNER = 0x0903,
	PCI_DEVICE_SUBCLASS_INPUT_DEVICE_CONTROLLER_GAMEPORT = 0x0904,
	PCI_DEVICE_SUBCLASS_INPUT_DEVICE_CONTROLLER_OTHER = 0x0980,

	PCI_DEVICE_SUBCLASS_DOCKING_STATION_GENERIC = 0x0A00,
	PCI_DEVICE_SUBCLASS_DOCKING_STATION_OTHER = 0x0A80,

	PCI_DEVICE_SUBCLASS_PROCESSOR_386 = 0x0B00,
	PCI_DEVICE_SUBCLASS_PROCESSOR_486 = 0x0B01,
	PCI_DEVICE_SUBCLASS_PROCESSOR_PENTIUM = 0x0B02,
	PCI_DEVICE_SUBCLASS_PROCESSOR_PENTIUM_PRO = 0x0B03,
	PCI_DEVICE_SUBCLASS_PROCESSOR_ALPHA = 0x0B10,
	PCI_DEVICE_SUBCLASS_PROCESSOR_POWERPC = 0x0B20,
	PCI_DEVICE_SUBCLASS_PROCESSOR_MIPS = 0x0B30,
	PCI_DEVICE_SUBCLASS_PROCESSOR_CO_PROCESSOR = 0x0B40,
	PCI_DEVICE_SUBCLASS_PROCESSOR_OTHER = 0x0B80,

	PCI_DEVICE_SUBCLASS_SERIAL_BUS_CONTROLLER_FIRE_WIRE = 0x0C00,
	PCI_DEVICE_SUBCLASS_SERIAL_BUS_CONTROLLER_ACCESS_BUS = 0x0C01,
	PCI_DEVICE_SUBCLASS_SERIAL_BUS_CONTROLLER_SSA = 0x0C02,
	PCI_DEVICE_SUBCLASS_SERIAL_BUS_CONTROLLER_USB = 0x0C03,
	PCI_DEVICE_SUBCLASS_SERIAL_BUS_CONTROLLER_FIBRE_CHANNEL = 0x0C04,
	PCI_DEVICE_SUBCLASS_SERIAL_BUS_CONTROLLER_SMBUS = 0x0C05,
	PCI_DEVICE_SUBCLASS_SERIAL_BUS_CONTROLLER_INFINIBAND = 0x0C06,
	PCI_DEVICE_SUBCLASS_SERIAL_BUS_CONTROLLER_IPMI_INTERFACE = 0x0C07,
	PCI_DEVICE_SUBCLASS_SERIAL_BUS_CONTROLLER_SERCOS_INTERFACE = 0x0C08,
	PCI_DEVICE_SUBCLASS_SERIAL_BUS_CONTROLLER_CANBUS = 0x0C09,
	PCI_DEVICE_SUBCLASS_SERIAL_BUS_CONTROLLER_OTHER = 0x0C80,

	PCI_DEVICE_SUBCLASS_WIRELESS_CONTROLLER_IRDA_COMPATIBLE = 0x0D00,
	PCI_DEVICE_SUBCLASS_WIRELESS_CONTROLLER_CONSUMER_IR = 0x0D01,
	PCI_DEVICE_SUBCLASS_WIRELESS_CONTROLLER_RF = 0x0D10,
	PCI_DEVICE_SUBCLASS_WIRELESS_CONTROLLER_BLUETOOTH = 0x0D11,
	PCI_DEVICE_SUBCLASS_WIRELESS_CONTROLLER_BROADBAND = 0x0D12,
	PCI_DEVICE_SUBCLASS_WIRELESS_CONTROLLER_ETHERNET_8021A = 0x0D20,
	PCI_DEVICE_SUBCLASS_WIRELESS_CONTROLLER_ETHERNET_8021B = 0x0D21,
	PCI_DEVICE_SUBCLASS_WIRELESS_CONTROLLER_OTHER = 0x0D80,

	PCI_DEVICE_SUBCLASS_INTELLIGENT_CONTROLLER_I20 = 0x0E00,

	PCI_DEVICE_SUBCLASS_SATELLITE_CONTROLLER_TV = 0x0F01,
	PCI_DEVICE_SUBCLASS_SATELLITE_CONTROLLER_AUDIO = 0x0F02,
	PCI_DEVICE_SUBCLASS_SATELLITE_CONTROLLER_VOICE = 0x0F03,
	PCI_DEVICE_SUBCLASS_SATELLITE_CONTROLLER_DATA = 0x0F04,
	PCI_DEVICE_SUBCLASS_SATELLITE_CONTROLLER_NETWORKAND_COMPUTING_ENCRPYTION_DECRYPTION = 0x1000,
	PCI_DEVICE_SUBCLASS_SATELLITE_CONTROLLER_ENTERTAINMENT_ENCRYPTION_DECRYPTION = 0x1010,
	PCI_DEVICE_SUBCLASS_SATELLITE_CONTROLLER_OTHER = 0x1080,

	PCI_DEVICE_SUBCLASS_SIGNAL_PROCESSING_CONTROLLER_DPIO_MODULES = 0x1100,
	PCI_DEVICE_SUBCLASS_SIGNAL_PROCESSING_CONTROLLER_PERFORMANCE_COUNTERS = 0x1101,
	PCI_DEVICE_SUBCLASS_SIGNAL_PROCESSING_CONTROLLER_COMMUNICATION_SYNCHRONIZER = 0x1110,
	PCI_DEVICE_SUBCLASS_SIGNAL_PROCESSING_CONTROLLER_SIGNAL_PROCESSING_MANAGEMENT = 0x1120,
	PCI_DEVICE_SUBCLASS_SIGNAL_PROCESSING_CONTROLLER_OTHER = 0x1180,
} DeviceSubclass;

typedef enum : uint8_t
{
	PCI_HEADER_TYPE_GENERAL = 0,
	PCI_HEADER_TYPE_PCI_TO_PCI_BRIDGE = 1,
	PCI_HEADER_TYPE_PCI_TO_CARD_BUS_BRIDGE = 2,
} HeaderType;

typedef struct 
{
	uint16_t ioSpace : 1;
	uint16_t memorySpace : 1;
	uint16_t busMaster : 1;
	uint16_t specialCycles : 1;
	uint16_t memoryWriteAndInvalidateEnable : 1;
	uint16_t vgaPaletteSnoop : 1;
	uint16_t parityErrorResponse : 1;
	uint16_t reserved : 1;
	uint16_t serrEnable : 1;
	uint16_t fastBackToBackEnable : 1;
	uint16_t interruptDisable : 1;
} __attribute__((packed)) CommandRegister;

typedef struct 
{
	uint16_t reserved0 : 3;
	uint16_t interruptStatus : 1;
	uint16_t capabilitiesList : 1;
	uint16_t capable66MHz : 1;
	uint16_t reserved1 : 1;
	uint16_t fastBackToBackCapable : 1;
	uint16_t masterDataParityError : 1;
	uint16_t devselTiming : 2;
	uint16_t signaledTargetAbort : 1;
	uint16_t receivedTargetAbort : 1;
	uint16_t signaledSystemError : 1;
	uint16_t detectedParityError : 1;
} __attribute__((packed)) StatusRegister;

typedef struct 
{
	uint16_t vendor, device;
	CommandRegister command;
	StatusRegister status;
	uint8_t revision;
	uint8_t progif;

	union 
	{
		DeviceSubclass subclass;
		struct 
		{
			uint8_t reserved;
			DeviceClass class;
		};
	};

	uint8_t cacheLineSize;
	uint8_t latencyTimer;
	HeaderType headerType;
	uint8_t bist;
} __attribute__((packed)) CommonHeader;

typedef struct 
{
	CommonHeader base;
	uint32_t BAR0, BAR1, BAR2, BAR3, BAR4, BAR5;
	uint32_t cardbusCisPointer;
	uint16_t subsystemVendor, subsystem;
	uint32_t expansionROMPointer;
	uint8_t capabilitiesPointer;
	uint8_t reserved[7];
	uint8_t interruptLine, interruptPin, minGrant, maxLatency;
} __attribute__((packed)) GeneralDevice;

bool pci_exists(uint8_t bus, uint8_t device, uint8_t function, HeaderType* type);
uint32_t pci_read_uint32(uint8_t bus, uint8_t device, uint8_t function, uint8_t offset);
uint16_t pci_read_uint16(uint8_t bus, uint8_t device, uint8_t function, uint8_t offset);
uint8_t pci_read_uint8(uint8_t bus, uint8_t device, uint8_t function, uint8_t offset);
void pci_read_header(uint8_t bus, uint8_t device, uint8_t function, CommonHeader* header);
void pci_enumerate_devices(void(*func)(CommonHeader header));

#endif
