#ifndef APIC_H
#define APIC_H

#include <stdint.h>

#define APIC_BASE_MSR 0x1B
#define APIC_BASE_MSR_BSP 0x100
#define APIC_BASE_MSR_ENABLE 0x800

#define APIC_REGISTER_OFFSET_LAPIC_ID 0x020
#define APIC_REGISTER_OFFSET_LAPIC_VERSION 0x030
#define APIC_REGISTER_OFFSET_TASK_PRIORITY 0x080
#define APIC_REGISTER_OFFSET_ARBITRATION_PRIORITY 0x090
#define APIC_REGISTER_OFFSET_PROCESSOR_PRIORITY 0x0A0
#define APIC_REGISTER_OFFSET_EOI 0x0B0
#define APIC_REGISTER_OFFSET_REMOTE_READ 0x0C0
#define APIC_REGISTER_OFFSET_LOGICAL_DESTINATION 0x0D0
#define APIC_REGISTER_OFFSET_DESTINATION_FORMAT 0x0E0
#define APIC_REGISTER_OFFSET_SPURIOUS_INTERRUPT_VECTOR 0x0F0
#define APIC_REGISTER_OFFSET_IN_SERVICE 0x100
#define APIC_REGISTER_OFFSET_TRIGGER_MODE 0x180
#define APIC_REGISTER_OFFSET_INTERRUPT_REQUEST 0x200
#define APIC_REGISTER_OFFSET_ERROR_STATUS 0x280
#define APIC_REGISTER_OFFSET_LVT_CORRECTED_MACHINE_CHECK_INTERRUPT 0x2F0
#define APIC_REGISTER_OFFSET_INTERRUPT_COMMAND 0x300
#define APIC_REGISTER_OFFSET_LVT_TIMER 0x320
#define APIC_REGISTER_OFFSET_LVT_THERMAL_SENSOR 0x330
#define APIC_REGISTER_OFFSET_LVT_PERFORMANCE_MONITORING_COUNTERS 0x340
#define APIC_REGISTER_OFFSET_LVT_LINT0 0x350
#define APIC_REGISTER_OFFSET_LVT_LINT1 0x360
#define APIC_REGISTER_OFFSET_LVT_ERROR 0x370
#define APIC_REGISTER_OFFSET_INITIAL_COUNT 0x380
#define APIC_REGISTER_OFFSET_CURRENT_COUNT 0x390
#define APIC_REGISTER_OFFSET_DIVIDE_CONFIGURATION 0x3E0

void apic_set_base(void* value);
void* apic_get_base(void);
uint32_t apic_register_read(int offset);
void apic_register_write(int offset, uint32_t value);
void apic_initialize(void);

#endif
